[package]
name = "rust-opengl-glfw-gl"
version = "0.1.0"
authors = ["dmyTRUEk <m.dmytruk21@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "0.37.0"
gl = "0.14.0"
